### PR TITLE
Fix software display rotation (again)

### LINKED ISSUE #351: DisplayOrientation setting does not rotate the screen
I intend to run XCSoar in bare KMS mode (i.e. not in X11 or Wayland window) and compiling it with `ENABLE_MESA_KMS=y` option. The display is portrait-oriented and I want to make XCSoar render the UI rotated 90 degrees on my screen. There is DisplayOrientation setting on xcsoar profile that seem to be supposed to do that, however it doesn't seem to do it correctly: the graphics seem to be rendered on portrait-oriented canvas, but then stretched on the landscape-oriented screen (see screenshot below).

The end goal is to run it in this mode on Openvario device (https://github.com/Openvario/meta-openvario/issues/2), but the issue doesn't seems to be specific to that device - I can reproduce it on my laptop as well.

To reproduce, I'm building the XCSoar on my laptop (Thinkpad T460 with Intel HD Graphics 520 GPU) with this command line:

```
make -j$(nproc) ENABLE_MESA_KMS=y
```

I have changed my `~/.xcsoar/default.prf` to include `DisplayOrientation="1"` line. To run XCSoar, I switch to linux console (Ctrl-Alt-F3) and start XCSoar normally: `output/UNIX/bin/xcsoar -fly`.

What I get as a result is on the photo below. I expect to see UI rotated 90 degrees instead, so it is usable if I orient display in portrait mode.

IMG_20200222_125450

While looking into it, I've found this piece of code in `src/Screen/OpenGL/Init.cpp`:
```c
UnsignedPoint2D
OpenGL::SetupViewport(UnsignedPoint2D size)
{
  window_size = size;

  glViewport(0, 0, size.x, size.y);

#ifdef SOFTWARE_ROTATE_DISPLAY
  projection_matrix = glm::rotate(glm::mat4(1),
                                  (GLfloat)Angle::Degrees(OrientationToRotation(display_orientation)).Radians(),
                                  glm::vec3(0, 0, 1));
  OrientationSwap(size, display_orientation);
#endif
  projection_matrix = glm::ortho<float>(0, size.x, size.y, 0, -1, 1);
  UpdateShaderProjectionMatrix();

  viewport_size = size;

  return size;
}
```

Note, that `projection_matrix` is assigned to some rotating matrix inside `SOFTWARE_ROTATE_DISPLAY` (which is indeed defined) block, and then immediately reassigned to `glm::ortho` matrix after that block. First assignment seems to be effectively lost. Naively commenting out the second assignment does not result in the rotated display though, but corrupts it (I end up with white rectangle on black screen).

That said, are my expectations of how `DisplayOrientation` works correct (is it supposed to rotate the whole screen)? Does the code I mentioned looks like a bug? Maybe there is some other way to achieve the rotation?

### PR DESCRIPTION
**Pull request by kedder**
Initial fix (8bd49afa25e112f3d5f377dfa1ad72656effc35d) caused rendering problems (black screen) on platforms in which `SOFTWARE_ROTATE_DISPLAY` is not defined (e.g. Android). It was reverted in 6ef5768a073f7fd07442dc6f897f4fe7220d460e.

Tested on Android, but was reproducible on regular UNIX as well. The problem with original `projection_matrix *= glm::ortho` fix is that `projection_matrix` is initialized with zero matrix.

Fixes #351.

### CODE REVIEW

**Comment by roeles** [comment]
Hm, sorry about breaking it.
Thanks for taking the time to fix the bug I introduced!

File: src/Screen/OpenGL/Init.cpp [hunk 1]
```diff
@@ -322,12 +322,15 @@ OpenGL::SetupViewport(UnsignedPoint2D size)
...
-  projection_matrix = glm::rotate(glm::mat4(1),
-                                  (GLfloat)Angle::Degrees(OrientationToRotation(display_orientation)).Radians(),
-                                  glm::vec3(0, 0, 1));
+  glm::mat4 rot_matrix = glm::rotate(
+    glm::mat4(1),
+    (GLfloat)Angle::Degrees(OrientationToRotation(display_orientation)).Radians(),
+    glm::vec3(0, 0, 1));
   OrientationSwap(size, display_orientation);
+#else
+  glm::mat4 rot_matrix = glm::mat4(1);  // no rotation
```
Comment (MaxKellermann) [inline src/Screen/OpenGL/Init.cpp:331]: This adds overhead for targets which have no software rotation, by multiplying this matrix which is a no-op. Can we avoid that overhead?

**Comment by roeles** [comment]
I think that if you keep the code the same for #ifdef SOFTWARE_ROTATE_DISPLAY as in my patch, but keep the code identical to what it was before my patch for #if !defined(SOFTWARE_ROTATE_DISPLAY), that should be simple enough and optimal for all platforms?

**Comment by kedder** [comment]
@MaxKellermann good point. 

I was choosing between introducing another `#ifdef SOFTWARE_ROTATE_DISPLAY` block and duplucating `glm::ortho<float>(0, size.x, size.y, 0, -1, 1);` sentence (as @roeles suggested) and picked the former option. 

The thing is `glm::ortho` needs `size` in right orientation, that is set up by `OrientationSwap` - it needs to be executed before `glm::ortho`.

**Comment by kedder** [comment]
Is there anything I can improve here? Any concerns, suggestions?
