### PR TITLE
Fix SOFTWARE_ROTATE_DISPLAY on all non-Android OpenGL platforms

### LINKED ISSUE #2166: Display orientation setting (SOFTWARE_ROTATE_DISPLAY) broken on all non-Android OpenGL platforms
## Problem

The "Display orientation" setting (`DisplayOrientation` in profile) does not work correctly when set to non-default values (Portrait, Reverse Portrait, Reverse Landscape). This is a long-standing defect originally reported in #351.

While investigating #2163 (a regression in the projection matrix order), it became clear that the underlying `SOFTWARE_ROTATE_DISPLAY` mechanism has multiple bugs beyond the regression:

### Symptoms

- InfoBoxes disappear or appear upside down
- Map flips upside down on touch gestures
- Gesture drawing doesn't align with touch position
- Rendering appears stretched (wrong aspect ratio)
- Window layout uses physical dimensions instead of logical (rotated) dimensions
- Content offset from expected position (0,0 not in top-left corner)
- Blank areas on screen with content larger than visible area

### Screenshots from #2163

**Broken portrait display on OpenVario:**
Image

**Expected correct rendering:**
Image

### Original report from #351

IMG_20200222_125450

## Root Causes

Multiple issues in the `SOFTWARE_ROTATE_DISPLAY` implementation:

1. **BufferCanvas corrupts `OpenGL::window_size`**: `BufferCanvas::Begin()` overwrites the global `OpenGL::window_size` with buffer dimensions but `Commit()` didn't restore it, corrupting physical dimensions used by `SetDisplayOrientation()`.

2. **Missing input coordinate transformation (X11)**: X11 mouse events (`MOUSE_DOWN`, `MOUSE_UP`, `MOUSE_MOTION`, `MOUSE_WHEEL`) passed raw physical coordinates without transformation for software rotation, causing misaligned gestures and touch input.

3. **Missing input coordinate transformation (Wayland)**: Only `MOUSE_WHEEL` events used `GetTransformedPointerPosition()` for software rotation; `MOUSE_DOWN`, `MOUSE_UP`, and `MOUSE_MOTION` used raw coordinates.

4. **Projection matrix order (regression from 1e4b8fee4f)**: The orthographic projection was computed before `OrientationSwap()`, using native physical dimensions instead of logical rotated dimensions. This was also the specific regression reported in #2163.

5. **Wayland double-swap on orientation change**: When `SetDisplayOrientation()` called `Resize(logical_size)`, Wayland's `OnResize()` would resize the EGL surface to logical dimensions (wrong — should stay physical) and call `CheckResize()` again, applying `OrientationSwap()` a second time.

6. **Wayland `Window::size` set to physical dimensions**: `Window::Resize()` sets the private `Window::size` before calling `OnResize()`. When Wayland compositor configure events arrive with physical dimensions, `Window::size` gets permanently set to physical dims, causing the layout to use wrong dimensions. See #2165 for the architectural refactor proposal.

## Affected Platforms

All platforms with `SOFTWARE_ROTATE_DISPLAY` (all OpenGL platforms except Android and iOS):
- MESA_KMS (OpenVario, Raspberry Pi, Cubieboard)
- X11
- Wayland
- SDL
- Windows

## Fix Branch

`fix/351-software-rotate-display` — addresses issues 1-5 above. Issue 6 (Wayland Window::size) has a workaround but needs the architectural refactor tracked in #2165.

## Related

- #351 — Original report (2020): DisplayOrientation setting does not rotate the screen
- #2163 — Regression report: Display scaling broken on OpenVario (Cubie2)
- #2164 — PR fixing only the regression (issue 4 above)
- #2165 — Refactor proposal: Separate physical and logical window size

### PR DESCRIPTION
**Pull request by lordfolken**
## Summary

- Fix `BufferCanvas` corrupting `OpenGL::window_size` by saving/restoring it in `Begin()`/`Commit()`
- Fix missing input coordinate transformation for X11 mouse events under software rotation
- Fix missing input coordinate transformation for Wayland `MOUSE_DOWN`/`MOUSE_UP`/`MOUSE_MOTION` events
- Fix projection matrix computed before `OrientationSwap()`, using wrong dimensions
- Fix Wayland double-swap: `OnResize()` no longer resizes EGL surface or re-applies `OrientationSwap()` on orientation changes

## Test plan

- [x] Test all four `DisplayOrientation` values (0=Default, 1=Portrait, 2=Reverse Landscape, 3=Reverse Portrait) on Wayland
- [x] Test all four values on X11
- [ ] Test on MESA_KMS (OpenVario) if available
- [ ] Verify touch/mouse input aligns correctly with rotated display
- [ ] Verify gestures draw at correct screen position
- [ ] Verify InfoBoxes render correctly in all orientations
- [ ] Verify default orientation (no rotation) still works correctly

Fixes #2166
Related: #351, #2163, #2165

## Summary by CodeRabbit

* **New Features**
  * Consistent coordinate transformation across input systems and native-size handling for improved window configuration.

* **Bug Fixes**
  * More reliable redraws after orientation or rotation changes to avoid stale visuals.
  * Improved terrain slope precision via floating-point calculations.

* **Refactor**
  * Unified and simplified input/event and display-configuration flows for more predictable behavior.

### CODE REVIEW

**Comment by lordfolken** [comment]
@coderabbitai full review

File: src/Terrain/RasterRenderer.cpp [hunk 1]
```diff
@@ -411,16 +411,22 @@ RasterRenderer::GenerateSlopeImage(unsigned height_scale,
...
+          double(dd1) * double(dd1) +
+          dd2 * dd2;
+        const double mag = sqrt(square_mag);
         /* this is a workaround for a SIGFPE (division by zero)
            observed by our users on some Android devices (e.g. Nexus
            7), even though we did our best to make sure that the
            integer arithmetics above can't overflow */
         /* TODO: debug this problem and replace this workaround */
-        const int sval = num / int(mag|1);
+        const int sval = int(num / std::max(mag, 1.0));
```
Comment (groundhogxc) [inline src/Terrain/RasterRenderer.cpp:429]: Not sure if that was intended, or if that was some LLM tool overshooting the target of improving optics?
(This is integer arithmetic on purpose, because it is such a high workload on the system.
If KOBO has to do this with float, the poor thing might melt :) )

Comment (groundhogxc) [reply src/Terrain/RasterRenderer.cpp:429]: Actually,  I realized later I might have been wrong about this. Will investigate more. (A bit confusing that it is in an essentially unrelated commit/PR though.)

But what was being addressed with this change? Was there a rendering quality problem?
