### PR TITLE
Eliminate duplicate waypoints in list

### LINKED ISSUE #816: Duplicate Waypoints on short waypoint files
The waypoints  apperar twice.
It is a normal *.cup - File. Exportet from Strepla für LX9000

XCSoar versions having and not having the problem
-------------------------------------------------

Having:
XCSoar v7.19 (debian)
XCSoar7 v.20-Android
It's the same behavior an Windows 7.21-PC

Having not:
XCSoar 7.18 (debian)

Expected behavior
-----------------

A waypoint corresponds to a waypoint in the CUP-File

Actual behavior
---------------

2 identic waypoints corresponds to 1 waypoint in the CUP-File

Steps to reproduce the behavior
-------------------------------
* Load the attached file as the sole file
* Open the waypoint list via for example the guesture

Do you have any idea what may have caused this?
-----------------------------------------------

No Idea

Do you have an idea how to solve the issue?
-------------------------------------------

No. Sorry

### LINKED ISSUE #958: Waypoint list displays duplicate entries for .cup
XCSoar versions having and not having the problem
-------------------------------------------------

7.18 is OK
7.19 has the problem
Possibly introduced in 9533b1221259257112d658a97474dddf9957cc03

Expected behavior
-----------------

When using guesture "L", I expect to see the consolidated list of waypoints with each one appearing only once.

Actual behavior
---------------

If a .cup waypoint has both a Title and Code (fields 1 and 2) non-blank, it appears in the waypoint list twice

Steps to reproduce the behavior
-------------------------------

Using any .cup file with a line that has both Title and Code (field 1 and 2), on the map display guesture "L" to call up the waypoint list and you will see that entry twice in the list (not necessarily consecutive).

Do you have any idea what may have caused this?
-----------------------------------------------

Perhaps it was a small error when the second field support was introduced in 7.19 or it has to do with filtering on both fields.  If it is the latter, I would hope a solution can be found to support filtering and only show once.

Do you have an idea how to solve the issue?
-------------------------------------------

Not really.  I'm unfamiliar with the code.  I'm happy to help if I can get guidance.

### PR DESCRIPTION
**Pull request by GeekGoneOld**
Retains filtering name and shortname but deletes duplicates
(e.g. when the shortname is the same as the name).  Also
eliminates duplicates when distance is the filter.  Bonus: this
should slightly speed up rendering of the waypoints on the map.
Closes #958
Closes #816

Brief summary of the changes
----------------------------

Related issues and discussions
------------------------------

### CODE REVIEW

**Comment by GeekGoneOld** [comment]
I assume the failure of build-macos is not caused by the PR.  I didn't do anything with a jpeg library.

File: src/Waypoint/WaypointList.cpp [hunk 1]
```diff
@@ -62,3 +62,30 @@ WaypointList::SortByDistance(const GeoPoint &location) noexcept
 {
   std::sort(begin(), end(), WaypointDistanceCompare(location));
 }
+
+class WaypointNameCompare
```
Comment (MaxKellermann) [inline src/Waypoint/WaypointList.cpp:66]: What's the point of this class? It has no fields; this should better be a standalone function with no `this` pointer overhead, or maybe even a lambda.

File: src/Waypoint/WaypointList.cpp [hunk 2]
```diff
@@ -62,3 +62,30 @@ WaypointList::SortByDistance(const GeoPoint &location) noexcept
...
+WaypointList::SortByName() noexcept
+{
+  std::sort(begin(), end(), WaypointNameCompare());
+}
+
+void
+WaypointList::MakeUnique() noexcept
+{
+  auto new_end = std::unique(begin(), end(), [](WaypointListItem &a, WaypointListItem &b)
+                                        {return a.waypoint->name == b.waypoint->name;});
```
Comment (MaxKellermann) [inline src/Waypoint/WaypointList.cpp:89]: Why compare names? There could be two different waypoints with the same name (but different location, type etc.). That's not a good way to enforce unique waypoints, I think.

**Review by MaxKellermann — CHANGES_REQUESTED** [review]

**Comment by MaxKellermann** [comment]
Why sort by name again, anyway? The vector is already sorted.

File: src/Waypoint/WaypointList.cpp (hunk 1 above)
Comment (GeekGoneOld) [reply src/Waypoint/WaypointList.cpp:66]: I have changed it to a lambda

File: src/Waypoint/WaypointList.cpp (hunk 2 above)
Comment (GeekGoneOld) [reply src/Waypoint/WaypointList.cpp:89]: I'm happy to use the waypoint id.  That, of course, would be unique.  I used the name because I felt that it would be reasonable to expect the name to be unique (NOT the shortname) and I also felt it would be most reasonable to present the list in some order and the most reasonable order was by name.

If I use waypoint id as the uniqueness, I would have to sort twice (once by id then unique() then by name).

**Comment by GeekGoneOld** [comment]
> 

I don't believe that is true.  I used my .cup files (attached) and removed the sort.  It resulted in duplicates in the list (at the very bottom).
[cupfile.zip](https://github.com/XCSoar/XCSoar/files/9384272/cupfile.zip)

File: src/Waypoint/WaypointList.cpp (hunk 2 above)
Comment (GeekGoneOld) [reply src/Waypoint/WaypointList.cpp:77]: Rethinking it, if the name is unique, sorting by name would allow unique() to work as two with the same name would also have the same id and the second one would be eliminated even if we unique() on id!  As a bonus, we only sort once (by name).

Caution, though.  If, by chance, there were three with the same name in the list, two of which were the same id and the third a different waypoint, the list COULD contain a duplicate if the order was ID1, ID2, ID1.  I would consider this a very minor issue that would be acceptable as it is caused by non-unique names (which should be discouraged) and no data is lost to the user.

I have updated the PR to unique by id after sorting by name.

**Comment by MaxKellermann** [comment]
> > Why sort by name again, anyway? The vector is already sorted.
> 
> I don't believe that is true.

You're right - the list is sorted, but by the name by which it was inserted (which may be the primary name or the short name), not by its primary name.
