### PR TITLE
Fixed deprecation compilation warnings on cares.

### LINKED ISSUE #1520: c-ares: deprecation warnings for ares_init
```
src/event/net/cares/Channel.cxx:49:14: warning: 'ares_init' is deprecated: Use ares_init_options instead [-Wdeprecated-declarations]
  int code = ares_init(&channel);
             ^
./output/ANDROID/armeabi-v7a/lib/armv7a-linux-androideabi/include/ares.h:482:26: note: 'ares_init' has been explicitly marked deprecated here
CARES_EXTERN             CARES_DEPRECATED_FOR(ares_init_options) int ares_init(
                         ^
./output/ANDROID/armeabi-v7a/lib/armv7a-linux-androideabi/include/ares.h:153:22: note: expanded from macro 'CARES_DEPRECATED_FOR'
      __attribute__((deprecated("Use " #f " instead")))
                     ^
src/event/net/cares/Channel.cxx:62:18: warning: 'ares_getsock' is deprecated: Use ARES_OPT_EVENT_THREAD or ARES_OPT_SOCK_STATE_CB instead [-Wdeprecated-declarations]
  const auto s = ares_getsock(channel, socks, ARES_GETSOCK_MAXNUM);
                 ^
./output/ANDROID/armeabi-v7a/lib/armv7a-linux-androideabi/include/ares.h:649:14: note: 'ares_getsock' has been explicitly marked deprecated here
CARES_EXTERN CARES_DEPRECATED_FOR(
             ^
./output/ANDROID/armeabi-v7a/lib/armv7a-linux-androideabi/include/ares.h:153:22: note: expanded from macro 'CARES_DEPRECATED_FOR'
      __attribute__((deprecated("Use " #f " instead")))
                     ^
src/event/net/cares/Channel.cxx:162:5: warning: 'ares_gethostbyname' is deprecated: Use ares_getaddrinfo instead [-Wdeprecated-declarations]
    ares_gethostbyname(_channel, name, family, HostCallback, this);
    ^
./output/ANDROID/armeabi-v7a/lib/armv7a-linux-androideabi/include/ares.h:627:14: note: 'ares_gethostbyname' has been explicitly marked deprecated here
CARES_EXTERN CARES_DEPRECATED_FOR(ares_getaddrinfo) void ares_gethostbyname(
             ^
./output/ANDROID/armeabi-v7a/lib/armv7a-linux-androideabi/include/ares.h:153:22: note: expanded from macro 'CARES_DEPRECATED_FOR'
      __attribute__((deprecated("Use " #f " instead")))
                     ^
3 warnings generated.
```

### PR DESCRIPTION
**Pull request by ballfire**
C-ares has deprecated some of the functions used:
- ares_init -> substituted by ares_init_options
- ares_gethostbyname -> substituted by ares_getaddrinfo, had to change some types and auxiliary functions but should work ok
- ares_getsock -> Basically limited to 16 sockets, while the library can do much more, there's no easy substitute and fixing it would require wrting a callback that's called each time a socket has a change of state and maintain a list of sockets pending to do something (what was done, basically). I started to write such callback, but then noticed that the forward_list of pending sockets is maintained, but actually never used ; so removed the list altogether

Should close  #1520 

## Summary by CodeRabbit

* **New Features**
  * Added a family-aware DNS lookup overload; default lookup now queries both IPv4 and IPv6.

* **Performance**
  * DNS resolution now leverages event-driven socket notifications, reducing unnecessary wakeups and improving responsiveness.

* **Refactor**
  * DNS flow migrated to addrinfo-based handling and simplified watcher/timeout management for more reliable and maintainable resolution.

### CODE REVIEW

**Comment by ballfire** [comment]
Revisiting the sockets list ; I think I missed something

**Comment by lordfolken** [comment]
Thx for looking into this.

**Comment by lordfolken** [comment]
Sorry for the long wait. 
So in general i like the implementation. It seems much saner than what we had. 
Things to fix:
 - code style: don't add spaces, or newlines if not needed. 
 - commit messages: Please stick to the style we generally have: file/area: changes
 - no fixup commits such as the last commit
 - debug code should be also not be in the history.

File: src/event/net/cares/Channel.cxx [hunk 1]
```diff
@@ -2,6 +2,7 @@
 // Copyright CM4all GmbH
 // author: Max Kellermann <mk@cm4all.com>
 
+
```
Comment (lordfolken) [inline src/event/net/cares/Channel.cxx:5]: remove line.

File: src/event/net/cares/Channel.cxx [hunk 2]
```diff
@@ -42,36 +43,41 @@ class Channel::Socket {
...
+  int optmask = 0;
+  optmask |= ARES_OPT_SOCK_STATE_CB;
+
+  int code = ares_init_options(&channel,&options,optmask);
   if (code != 0) throw Error(code, "ares_init() failed");
 }
 
 Channel::~Channel() noexcept { ares_destroy(channel); }
 
+
```
Comment (lordfolken) [inline src/event/net/cares/Channel.cxx:76]: remove line

File: src/event/net/cares/Channel.cxx [hunk 3]
```diff
@@ -236,8 +228,8 @@ Channel::Lookup(const char *name, Handler &handler,
                 CancellablePointer &cancel_ptr) noexcept
 {
   auto *request = new Request(handler, 2, cancel_ptr);
-  request->Start(channel, name, AF_INET6);
   request->Start(channel, name, AF_INET);
+  request->Start(channel, name, AF_INET6);
   UpdateSockets();
```
Comment (lordfolken) [inline src/event/net/cares/Channel.cxx:233]: Hmm here you are deprioritizing ipv6. I would prefer ipv6 first.

File: src/event/net/cares/Channel.hxx [hunk 4]
```diff
@@ -61,11 +61,11 @@ public:
 
 private:
   void UpdateSockets() noexcept;
-
   void ScheduleUpdateSockets() noexcept { defer_update_sockets.Schedule(); }
-
   void OnSocket(SocketDescriptor fd, unsigned events) noexcept;
   void OnTimeout() noexcept;
+  static void sock_state_cb(void *data, ares_socket_t socket_fd, int readable, int writable);
+
```
Comment (lordfolken) [inline src/event/net/cares/Channel.hxx:68]: please remove line.

File: src/event/net/cares/Channel.cxx [hunk 5]
```diff
@@ -217,9 +206,12 @@ Channel::Request::HostCallback(int status, struct hostent *he) noexcept
       if (success) handler->OnCaresSuccess();
       else handler->OnCaresError(std::current_exception());
     }
+    ares_freeaddrinfo(addressinfo);
   }
 
+  ares_freeaddrinfo(addressinfo);
   if (pending == 0) delete this;
```
Comment (lordfolken) [inline src/event/net/cares/Channel.cxx:213]: This will potenially call ares_freeaddrinfo twice.

File: src/event/net/cares/Channel.cxx [hunk 6]
```diff
@@ -42,36 +43,41 @@ class Channel::Socket {
...
 }
 
 Channel::~Channel() noexcept { ares_destroy(channel); }
 
+
 void
 Channel::UpdateSockets() noexcept
 {
   timeout_event.Cancel();
-  sockets.clear();
```
Comment (lordfolken) [inline src/event/net/cares/Channel.cxx:59]: you are removing this. We need  a way to clear the sockets, otherwise we have a memory leak.

**Comment by lordfolken** [comment]
@coderabbit fullreview

**Comment by lordfolken** [comment]
Hmm i somehow screwed up the rebase.
